
language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq git cmake g++ gfortran libboost-all-dev libblas-dev liblapack-dev libeigen3-dev
  - sudo apt-get install -qq python-dev python3-pip
  - sudo apt-get install libopenmpi-dev openmpi-bin
  - pip3 install --upgrade numpy scipy
  - pip3 install pybind11 sphinx mpi4py
  - pip3 install pytest-cov pytest codecov

install:
  - mkdir build-expokitpy
  - cd build-expokitpy &&
    git clone https://github.com/weinbe58/expokitpy.git &&
    cd expokitpy &&
    pip3 install . &&
    cd ../..
  - mkdir build
  - cd build &&
    cmake .. -DBUILD_LIB=ON &&
    make -j 4 &&
    cd ..

script:
  - PYTHONPATH=.:./build py.test unit_test --cov-report term --cov=pyblock

after_success:
  - codecov
